service: hello-world 

plugins:
  - serverless-plugin-aws-cn-principal
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs8.10
  endpointType: regional
  region: cn-north-1
  iamRoleStatements:
    - Effect: Allow
      Action: dynamodb:scan
      Resource: arn:aws-cn:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/restaurants

functions:
  hello-world:
    handler: functions/hello-world.handler
    events:
      - http:
          path: /hello
          method: get

  get-restaurants:
    handler: functions/get-restaurants.handler
    events:
      - http:
          path: /restaurants
          method: get

resources:
  Resources:
    restaurantsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: restaurants
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1